### ISSUE TITLE
please add some doc

### ISSUE THREAD

**Issue by makemeunsee** [ReactiveSocket/reactivesocket-java-impl#12]
to the examples at least.
or is there a manual I am not aware of?

**Comment by stevegury** [comment]
Unfortunately, there isn't any hidden manual.
ReactiveSocket is still under ongoing development and it didn't reach stability yet. That's why we didn't spend the time to write any documentation.

That being said we could/will improve the comments in the examples.

**Comment by stevegury** [comment]
Closing, this repo will die in favor of reactivesocket-java.
